function jp_resetMatlabDefaults()
%JP_RESETMALTADEFAULTS resets some plotting defaults.
%
%
%  From https://github.com/jpeelle/jp_matlab

set(0,...
    'DefaultAxesLineWidth',.5, ...
    'DefaultAxesFontSize',10, ...
    'DefaultLineLineWidth',.5 ...
    )