function jp_setMatlabDefaults()
%SETMALTADEFAULTS set some defaults for plotting.
%
%
%  From https://github.com/jpeelle/jp_matlab

set(0,...
    'DefaultAxesLineWidth',1, ...
    'DefaultAxesFontSize',12, ...
    'DefaultLineLineWidth',1.5 ...
    )