function jp_setMatlabPosterDefaults()
%SETMALTABPOSTERDEFAULTS set some defaults for plotting.
%
%
%  From https://github.com/jpeelle/jp_matlab

set(0,...
    'DefaultAxesLineWidth',1, ...
    'DefaultAxesFontSize',18, ...
    'DefaultLineLineWidth',1.5 ...
    )