% Wrapper for jp_stringtogethersounds
%
%  From https://github.com/jpeelle/jp_matlab

clear all

%% SNRs

snrs = [-5:5:15];


%% List of soundfiles

files{1} = {'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0215_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0002_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0158_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0072_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0226_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0144_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0140_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0036_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0447_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0397_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0563_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0435_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0329_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0520_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0401_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0501_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0179_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0162_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0246_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0157_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0198_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0025_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0089_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0032_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0538_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0471_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0325_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0291_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0418_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0570_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0389_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0443_f1.wav'};


files{2} = {'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0250_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0011_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0090_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0125_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0197_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0021_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0053_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0088_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0490_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0420_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0312_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0531_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0422_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0407_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0550_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0493_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0083_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0043_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0001_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0107_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0095_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0122_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0210_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0026_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0454_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0476_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0542_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0299_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0400_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0505_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0541_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0413_f1.wav'};


files{3} = {'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0063_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0018_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0100_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0071_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0168_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0062_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0009_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0204_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0504_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0442_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0519_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0537_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0331_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0320_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0518_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0497_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0115_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0183_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0086_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0143_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0200_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0233_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0219_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0195_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0328_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0557_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0530_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0309_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0495_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0303_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0522_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0383_f1.wav'};


files{4} = {'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0206_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0181_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0145_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0042_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0281_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0038_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0176_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0258_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0358_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0388_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0332_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0556_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0408_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0321_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0539_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0543_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0035_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0225_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0208_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0239_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0254_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0218_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0248_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0074_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0559_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0469_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0484_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0480_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0387_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0506_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0453_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0421_f1.wav'};

files{5} = {'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0241_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0109_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0069_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0275_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0129_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0245_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0127_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0034_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0405_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0385_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0316_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0347_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0433_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0310_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0482_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0333_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0096_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0267_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0159_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0137_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0264_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0051_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0263_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0148_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0379_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0463_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0287_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0326_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0284_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0318_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0317_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0546_f1.wav'};


files{6} = {'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0236_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0276_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0103_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0052_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0166_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0229_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0156_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0131_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0523_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0444_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0399_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0301_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0366_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0294_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0353_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0551_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0104_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0260_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0252_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0037_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0272_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0213_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0182_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0187_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0414_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0375_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0390_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0449_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0429_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0568_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0571_f1.wav',...
'/Volumes/oto_secure$/Peelle_Lab/stimuli/sentencesA/Audio-only/A0448_f1.wav'};


%% Set options
Cfg = [];




%% Run blocks with no noise
outName = fullfile(pwd, 'longsound.wav',...');
[y, fs] = jp_stringtogethersounds(files, Cfg);
audiowrite(outName, y, fs);

%% Run options with noise (looping through SNRs)

Cfg.noiseFile = '/Volumes/oto_secure$/Peelle_Lab/stimuli/noise_sources/Heinrich_8talker_babble_44100.wav',...';
    
for Cfg.SNR = snrs
    outName = fullfile(pwd, 'longsound.wav',...');
[y, fs] = jp_stringtogethersounds(files, Cfg);
audiowrite(outName, y, fs);    
end
