function setMatlabDefaults()
%SETMALTADEFAULTS set some defaults for plotting.
%
% Jonathan Peelle 2005

set(0,...
    'DefaultAxesLineWidth',.5, ...
    'DefaultAxesFontSize',10, ...
    'DefaultLineLineWidth',.5 ...   
    )