function setMatlabDefaults()
%SETMALTADEFAULTS set some defaults for plotting.
%
% Jonathan Peelle 2005

set(0,...
    'DefaultAxesLineWidth',1, ...
    'DefaultAxesFontSize',12, ...
    'DefaultLineLineWidth',1.5 ...   
    )